name: CI

on:
  push:
    branches:
    - master
    paths-ignore:
    - '**.org'
  release:
    types: [published]
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
    - '**.org'

env:
  DOCKER_BASE_NAME: docker.pkg.github.com/${{ github.repository }}/yaskkserv2
  DOCKER_HUB_BASE_NAME: lurdan/yaskkserv2

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - run: docker run --rm -i
        -v "$PWD"/.hadolint.yaml:/opt/.config/hadolint.yaml
        -e XDG_CONFIG_HOME=/opt/.config
        hadolint/hadolint < Dockerfile

  push:
    runs-on: ubuntu-latest
    needs: hadolint
    steps:
    - uses: actions/checkout@master
      with:
         fetch-depth: 1
    - name: setenv
      run: |
        if [ "${{ github.event_name }}" = 'release' ]
        then
          export TAG_NAME="${{ github.event.release.tag_name }}"
        else
          export TAG_NAME="latest"
        fi
        echo "PKG_TAG=${DOCKER_BASE_NAME}:${TAG_NAME}" >> $GITHUB_ENV
        echo "HUB_TAG=${DOCKER_HUB_BASE_NAME}:${TAG_NAME}" >> $GITHUB_ENV

    - name: build and check
      run: |
        ./util.sh build "${PKG_TAG}"
        docker tag "${PKG_TAG}" "${HUB_TAG}"
        docker run --rm ${PKG_TAG} /usr/local/bin/yaskkserv2 --version
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
        -v ${HOME}/.cache:/root/.cache aquasec/trivy:latest --exit-code 1 ${PKG_TAG}

    - name: push to registry
      if: github.event_name != 'pull_request'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      run: |
        echo "${GITHUB_TOKEN}" | docker login docker.pkg.github.com -u lurdan --password-stdin
        echo "${DOCKER_HUB_TOKEN}" | docker login -u lurdan --password-stdin
        docker push "${PKG_TAG}"
        docker push "${HUB_TAG}"
